"""
Dataset Audit Script for Smart Health Monitoring IoT System.
Inspects all datasets and reports shape, columns, missing values, and selection decisions.
"""

import os
import sys

import pandas as pd

DATASETS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "datasets")

DATASET_INFO = {
    "Synthetic_patient-HealthCare-Monitoring_dataset.csv": {
        "status": "USED",
        "use_case": "Primary — vital signs, fall detection, alert labels, status classification",
        "reason": "Contains HR, SpO2, BP, temperature, fall detection, per-vital alert labels, predicted disease."
    },
    "human_vital_signs_dataset_2024.csv": {
        "status": "USED",
        "use_case": "Primary — risk classification with demographics and derived features",
        "reason": "Contains vitals + demographics + derived features + labeled Risk Category."
    },
    "personal_health_data.csv": {
        "status": "USED",
        "use_case": "Primary — anomaly detection and risk regression",
        "reason": "Contains Health_Score for risk, Anomaly_Flag for supervised anomaly detection."
    },
    "patients_data_with_alerts.xlsx": {
        "status": "USED",
        "use_case": "Secondary — additional alert labels for status classifier",
        "reason": "Provides mixed-case alert labels for training status classification."
    },
    "healthcare_iot_target_dataset_5000.csv": {
        "status": "USED",
        "use_case": "Secondary — IoT health status targets and battery level",
        "reason": "IoT-specific targets with device battery level feature."
    },
    "heart_rate.csv": {
        "status": "USED",
        "use_case": "Primary — heart rate time series forecasting",
        "reason": "Four independent HR time series (T1-T4) for lag-based forecasting model."
    },
    "Oxygen Dataset Final.csv": {
        "status": "USED",
        "use_case": "Secondary — supplements anomaly detection with SpO2 data",
        "reason": "SpO2, pulse rate, oxygen flow for oxygen-specific anomaly features."
    },
    "Health data.csv": {
        "status": "USED",
        "use_case": "Supplementary — lightweight dataset for additional training samples",
        "reason": "Contains pulse, body temperature, SpO2, and status labels."
    },
    "digital_interaction_data.csv": {
        "status": "EXCLUDED",
        "use_case": "None",
        "reason": "Contains only Notifications_Received and Screen_Time — digital behavior, not health sensors."
    },
    "activity_environment_data.csv": {
        "status": "EXCLUDED",
        "use_case": "None",
        "reason": "Mixes activity data with non-health environmental data (UV, Altitude, Ambient_Temperature)."
    },
    "healthcare_patient_journey.csv": {
        "status": "EXCLUDED",
        "use_case": "None",
        "reason": "Hospital administrative data (wait_time, cost, satisfaction) — not real-time IoT."
    },
    "Synthetic-Infant-Health-Data.csv": {
        "status": "EXCLUDED",
        "use_case": "None",
        "reason": "Pediatric cardiac disease data — does not align with adult health monitoring."
    },
    "diabetes_dataset.csv": {
        "status": "EXCLUDED",
        "use_case": "None",
        "reason": "Static disease classification dataset — not a real-time IoT sensor stream."
    },
    "updated_version.csv": {
        "status": "EXCLUDED",
        "use_case": "None",
        "reason": "Cardiovascular risk/cholesterol data — not generated by real-time wearable sensors."
    },
}


def audit_dataset(filepath, name):
    """Audit a single dataset file."""
    info = DATASET_INFO.get(name, {"status": "UNKNOWN", "use_case": "Unknown", "reason": "Not categorized"})

    print(f"\n{'=' * 70}")
    print(f"  DATASET: {name}")
    print(f"{'=' * 70}")

    try:
        if filepath.endswith(".xlsx"):
            df = pd.read_excel(filepath)
        else:
            df = pd.read_csv(filepath)

        print(f"  Shape:       {df.shape[0]} rows × {df.shape[1]} columns")
        print(f"  Columns:     {list(df.columns)}")
        print(f"  Status:      {info['status']}")
        print(f"  Use case:    {info['use_case']}")
        print(f"  Reason:      {info['reason']}")

        missing = df.isnull().sum()
        missing_cols = missing[missing > 0]
        if len(missing_cols) > 0:
            print(f"  Missing values:")
            for col_name, count in missing_cols.items():
                print(f"    {col_name}: {count} ({count/len(df)*100:.1f}%)")
        else:
            print(f"  Missing values: None")

        print(f"  Dtypes:      {dict(df.dtypes.value_counts())}")

    except FileNotFoundError:
        print(f"  ERROR: File not found at {filepath}")
    except Exception as e:
        print(f"  ERROR: Could not read file — {e}")


def main():
    print("=" * 70)
    print("  SMART HEALTH MONITORING IoT — DATASET AUDIT REPORT")
    print("=" * 70)
    print(f"  Datasets directory: {DATASETS_DIR}")

    if not os.path.isdir(DATASETS_DIR):
        print(f"  ERROR: Datasets directory not found: {DATASETS_DIR}")
        sys.exit(1)

    # List all files in datasets/
    all_files = sorted(os.listdir(DATASETS_DIR))
    dataset_files = [f for f in all_files if f.endswith((".csv", ".xlsx"))]

    print(f"  Total dataset files found: {len(dataset_files)}")

    used_count = 0
    excluded_count = 0

    for filename in dataset_files:
        filepath = os.path.join(DATASETS_DIR, filename)
        audit_dataset(filepath, filename)
        info = DATASET_INFO.get(filename, {})
        if info.get("status") == "USED":
            used_count += 1
        elif info.get("status") == "EXCLUDED":
            excluded_count += 1

    print(f"\n{'=' * 70}")
    print(f"  SUMMARY")
    print(f"{'=' * 70}")
    print(f"  Total datasets: {len(dataset_files)}")
    print(f"  USED:           {used_count}")
    print(f"  EXCLUDED:       {excluded_count}")
    print(f"  UNCATEGORIZED:  {len(dataset_files) - used_count - excluded_count}")
    print(f"{'=' * 70}")


if __name__ == "__main__":
    main()
